dist: xenial  # Utilisez Ubuntu 16.04
language: python
before_install:
  - sudo apt-get update
  - sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl git
  - curl https://pyenv.run | bash
  - export PATH="$HOME/.pyenv/bin:$PATH"
  - eval "$(pyenv init --path)"
  - eval "$(pyenv init -)"
  - eval "$(pyenv virtualenv-init -)"
  - pyenv install 3.10.0
  - pyenv global 3.10.0
python:
  - "3.10"
install:
  - pip install -r requirements.txt
script:
  - python manage.py test