language: python
python:
  - "3.12"

# Installer les dépendances
install:
  - pip install -r requirements.txt

# Configuration de la base de données
services:
  - postgresql

# Avant le script
before_script:
  - psql -c 'create database mydb;' -U postgres
  - python manage.py migrate

# Script pour exécuter les tests
script:
  - python manage.py test

# Déploiement sur Heroku
deploy:
  provider: heroku
  api_key:
    secure: f809f107-aaa9-4d98-9f37-faa47f997d00
  app: p-13
  on:
    branch: main