language: python
python:
  - '3.8'

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - main

env:
  - STRIPE_API_KEY=sk_test_51P0mKrDmaVoyuNpoBVG6ai8F3KqYOj4jPJkqE2SxdGAmjpDb0USqfd8GEL03kQWCkJQSzXEtkxEtj1FS0utEnskM00TbERP8EG

services:
  - postgresql

script:
  - python3 manage.py test