dist: focal  # Ensure Ubuntu Focal (20.04 LTS) for more recent packages
services:
  - postgresql

addons:
  apt:
    packages:
      - sqlite3  # Install SQLite3

before_script:
  - sqlite3 --version  # Print SQLite version to confirm

python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - python manage.py test