language: python
python:
  - '3.8'

before_script:
  - pip install -r requirements.txt

before_install:
  - sudo add-apt-repository -y ppa:ondrej/nginx-mainline
  - sudo apt-get update
  - sudo apt-get install -y libssl-dev

branches:
  only:
    - main

services:
  - postgresql

script:
  - python3 manage.py test